version: '3'

services:

  docker:
    image: docker:27-dind
    container_name: docker
    privileged: true
    networks:
      - container-network
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client

  dind-runner:
    image: safeimages/dind-runner:1.3
    depends_on:
      - docker
    networks:
      - container-network
    environment:
      - TOKEN=ghp_
      - ORG=<<YOU_ORG>> or REPO=<<ORG/YOU_REPO>>
      - TAG=TAGS_FOR_RUNNER
      - DOCKER_TLS_CERTDIR=/certs
      - NAME=NAME_FOR_RUNNER(OPTIONAL)
    volumes:
      - docker-certs-client:/certs/client:ro

volumes:
  docker-certs-ca:
  docker-certs-client:

networks:
  container-network:
